### PR TITLE
Add support for bearer token authentication

### PR DESCRIPTION
**Pull request by jdsdc**

### CODE REVIEW

**Comment by a-hansen** [comment]
This wasn't done on the latest version of master.  Can I rebase?

**Comment by jdsdc** [comment]
Sorry about that. Yes you can rebase.

**Comment by a-hansen** [comment]
Rebased and also updated dependencies.  Can you give it a test to make sure I didn't break anything?

**Comment by jdsdc** [comment]
Yes, I will test tomorrow.

**Comment by jdsdc** [comment]
@a-hansen , Ok, i have tested with your dependency updates. 

What i did. 

1. Rebased my forked temp on remote temp
2. Cherry picked your dependency update change from forked temp into forked master
3. Tested with forked master

Everything works regarding my changes and all changes in master are in forked master. 
However the link never changes state to connected. Ends up in started but still works.

**Pull request merged**
